{% set name = "redflag" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redflag-{{ version }}.tar.gz
  sha256: 079e82c842544ed51bdbe77119bc60507dc87fb49752d5df65f02845dc8b60a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=68
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.8
    - numpy <2.0
    - scipy !=1.10.0
    - scikit-learn

test:
  imports:
    - redflag
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://scienxlab.org/redflag/
  summary: Raise red flags on machine learning datasets.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwinkunks
